### ISSUE TITLE
A newer migration strategy with moved blocks

### ISSUE THREAD

**Issue by Puneeth-n** [clowdhaus/eks-v17-v18-migrate#2]
We are migrating from v17 to v18. Given that we have now `moved` blocks, can we some how have an adapted solution to this issue?

Especially a solution that does not involve "forget"ing and draining the old EKS MNG as this wouldn't be feasible for us as we have close to 300 EKS clusters

**Comment by bryantbiggs** [comment]
you can use moved blocks if you wish, but its not something that will be defined here since most of that content will be specific to individual use cases
